# Generated by Django 3.1.5 on 2021-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_managementapproach_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementapproach',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programmaticapproach',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
