# Generated by Django 3.1.5 on 2021-02-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20210129_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementapproach',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
        migrations.AlterField(
            model_name='programmaticapproach',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.program'),
        ),
    ]
