# Generated by Django 3.1.5 on 2021-01-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='category',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Government', 'Government'), ('NGO', 'NGO'), ('For Profit', 'For Profit'), ('Inter-Governmental', 'Inter-Governmental'), ('Diplomatic Missions', 'Diplomatic Missions')], max_length=100, null=True),
        ),
    ]
